title: SkyrScout
description: Independent football scouting project
theme: null

collections:
  players:
    output: true
    permalink: /players/:name/

  news:
    output: true
    permalink: /news/:name/

defaults:
  - scope:
      path: ""
      type: "players"
    values:
      layout: player
