title: SkyrScout
description: Independent football scouting project
theme: null

collections:
  players:
    output: true
    permalink: /players/:name/

  update_posts:
    output: true
    permalink: /updates/:name/

defaults:
  - scope:
      path: ""
      type: "players"
    values:
      layout: player

  - scope:
      path: ""
      type: "update_posts"
    values:
      layout: updates
