title: SkyrScout
description: Independent football scouting project

url: "https://skyrscout.github.io"
baseurl: ""

theme: null

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  players:
    output: true
    permalink: /players/:name/

  shorts:
    output: true
    permalink: /shorts/:name/

  update_posts:
    output: true
    permalink: /updates/:name/

defaults:
  - scope:
      path: ""
      type: "players"
    values:
      layout: player

  - scope:
      path: ""
      type: "shorts"
    values:
      layout: short

  - scope:
      path: ""
      type: "update_posts"
    values:
      layout: updates

google_analytics: "G-JR894EKXF4"
exclude:
  - development/
